dikshantmali/Hacktoberfest2020-HTML-CSS-WEB

- Parallax/alka_trivedi.css
- Parallax/alka_trivedi.html
Illustration of Parallax Scrolling using HTML and CSS. Thank you:)
> ParallaxScrolling

- css/navbar.css
- html/navbar.html
> added horizontal navbaar

- tejan-singh_error404page.html
for my contribution to Hacktoberfest 2020!
> add tejan-singh_error404page.html

- Loader for Webpage/loader.html
- Loader for Webpage/loaderStyle.css
Added a lovely loader for webpage!
> #1 issue: Added loader to webpage

- Navbar/css/pagecomic.css
- Navbar/pagecomic.html
> DOC : my new page 

- README.md
I have made a few changes, let me know if I can improve it any further
> readmeUpdated

- Type of form/index.html
> add type of form

- facebook_login/facebook.html
- facebook_login/fb.css
I made a **Facebook** login webpage. @dikshantmali please have a look at it.
> Facebook login webpage

- error 404 HTML/404.css
- error 404 HTML/error404page.html
added custom css for 404 message
> fet(404) custom style

- knob/index.html
- knob/knob.css
Hello, here is my contribution
Changelog :spiral_notepad: 
* Add a knob made with html/css
Picture :framed_picture:
> Add a knob made with html and css

- Portfolio-template/index.html
> added simple bootstrap portfolio template

- facebook_login/facebook.html
- facebook_login/fb.css
- Added styling to buttons
- removed overflow to elements and aligned them properly (in form sec)
- optimized the CSS
> Removed the overflow and corrected the orientation of the fb page

- Type of form/index.html
> add bootstrap 4 stacked form

- Automated Covid19 Pass/app.js
Changes made to pdf gen and variables due to mistakes
#hacktoberfest2020
> Updated App.js and pdf gen deleted 

- Calculator/index.html
- Calculator/script.js
- Calculator/stylesheet.css
A web app to calculate simple numbers. Fully functional.
Issue: #1
> Calculator

- Envelop Animation/index.html
- Envelop Animation/style.css
@dikshantmali please merge this please
> Add Envelop Hover Animation to this repo

- Image hover animations/index.html
- Image hover animations/styles.css
add 3 image hover for beginners, only with css
> add image hover animation folder

- Absolute-Center-Fullscreen-Layout/css/style.css
- Absolute-Center-Fullscreen-Layout/index.html
The example I added shows a newbie how to do absolute center (and fullscreen divs) using vanila CSS in as few lines as possible.
> Added 'absolute center with vanilla css' Example

- Table-calculate-basic/css/table.css
- Table-calculate-basic/table.html
> Basic table calculate

- simple-parallax-effect/index.html
this simple project parallax effect example
> simple-parallax-effect

- Covid stats viewer/covid-19 stats.html
- Covid stats viewer/styles.css
- Extracted css
- Adjusted indentation and spacing for imprived readability
> Extracted css to a seperate file

- css model/css/styles.css
- Fix indentation and spacing
- Remove unused style (#title)
> Fix indentation and spacing of css

- Calculator/index.html
- Calculator/stylesheet.css
Added css animation to the calculator file.
> added animation to calculator file

- Gratis/.vscode/settings.json
- Gratis/html/footer.html
I have added a new Footer HTML page and in the Gratis folder.
> Added a Footer

- CSS Visual Editor/index.html
- CSS Visual Editor/script.js
- CSS Visual Editor/styles.css
**@dikshantmali please review**
> Create CSS Visual Editor 

- Custom Loader/app.js
- Custom Loader/index.html
- Custom Loader/styles.css
> Fix:#89 Added Custom Loader

- Randon Color/index.html
- Randon Color/script.js
- Randon Color/styles.css
Added a random color picker.
I am grateful if anyone wants to review the code and point me to possible improvements.
> Added a random color picker.

- MouseClock/app.css
- MouseClock/app.js
- MouseClock/index.html
Added code for mouse to be followed by the clock
> Add Mouse clock

- Dropdown-div-based/app.css
- Dropdown-div-based/app.js
- Dropdown-div-based/index.html
* Generating dropdown from html divs grouped with options.
* Just add the appropriate styles and you should be done
> Added div based dropdown

- Pure-css-expand-collapse/app.css
- Pure-css-expand-collapse/index.html
With this PR:
* We can create a component to expand and collapse any div with pure CSS
Collapsed state
Expanded state
> Add pure css expand and collapse component

- AlarmClock/README.md
- Image hover animations/README.md
See content of README.md down below.
> add README to AlarmClock and Image hover animations

- basic-dom-manipulation/css.css
- basic-dom-manipulation/index.html
- basic-dom-manipulation/index.js
This is a simple JavaScript game with comments in the html and js files to explain basic DOM manipulation.
> Guess the number game

- Adding mobile compatible videos/index.html
See whether you like this better. I think it is more professional.
This is a Hacktoberfest contribution.
> Make small text corrections

- Adding mobile compatible videos/README.md
This is the second README I created.
I think the text you use in this app is not entirely correct English so I will send you a new version to have a look at. If you like it, you can merge it. This is a Hacktoberfest contribution.
> Create README.md for directory Adding mobile compatible videos

- .vscode/settings.json
- Absolute-Center-Fullscreen-Layout/README.md
Hi Dikshant, let me know if this is what you are looking for. I participate in Hacktoberfest, I am a reliable and conscientious coder so I can help you with this. It is an amazing repo with good work!
Note: This is a Hacktoberfest contribution.
> Create README.md for directory Absolute Center Fullscreen Layout

- playSound/README.md
- playSound/index.html
- playSound/playSound.js
This is the code to play a sound when the user clicks a button. There is no styling of the button and the code is clear and basic for anyone to adapt to their wishes. I am adding this app as part of my contributions to your project during the Hacktoberfest.
> Hacktoberfest: Add a small app with code to play a sound when a button is clicked

- Calculator-PHP/index.php
Hello, this is my creation called PHP Web Calculator
im used PHP and HTML for this project
> PHP Web Calculator

- Netflix Home Page/index.css
- Netflix Home Page/index.html
1. Added inner shadow (vintage effect) to cover background image.
2. Added left and top margin to logo.
3. Increased the size of logo.
> Updated cover image and Netflix logo

- radom_name_generator_game/README.md
- radom_name_generator_game/index.html
- radom_name_generator_game/script.js
- radom_name_generator_game/style.css
> random-name-generator

- Analog Clock/alarm.js
- Analog Clock/clock.html
- Analog Clock/stylea.css
> Add Mayank-Khurmai to Contributors for hacktoberfest

- registration_form/tanvi_form.html
> Registration Form

- Website/.htaccess.txt
- Website/contact.html
- Website/family.html
- Website/gallery.html
- Website/index html
- Website/membership.html
I have made a website on my own. http://bbksamiti.ezyro.com
> Added a Website

- error 404 HTML-CSS-2/README.md
- error 404 HTML-CSS/README.md
- facebook_login/README.md
This PR is to add a readme for the folders:
- Error 404 HTML-CSS
- Error 404 HTML-CSS-2
- Facebook Login
> add(readme): added the readme for the error 404 and facebook login

- animationsRotate/rotate90deg.html
- animationsRotate/rotateCenter.html
- animationsRotate/rotateDiagonal.html
- animationsRotate/rotateScaleUp.html
#11  new animations rotate :+1:
> feat: add my rotate animations

- BASIC HTML PAGES/Ecommerce_website.html
- BASIC HTML PAGES/Registration_form.html
Added two Basic HTML Pages
1. Registration Form
2. E-Commerce Website
> Added Basic HTML Pages

- Absolute-Center-Fullscreen-Layout/Kelechi-Eluagu.html
- Absolute-Center-Fullscreen-Layout/css/Kelechi-Eluagu.css
I added a simple center full-screen layout in the absolute-center-fullscreen-layout folder
> added an absolute center full screen layout

- contact-form using html css/about.html
- contact-form using html css/contact.html
- contact-form using html css/index.html
- contact-form using html css/style.css
Added my experience for this hacktoberfest. Created html and css files.
> Added my website having home and contact page

- Quote of the day/index.html
> add quote of the day webpage

- CurrentTime/README.md
- CurrentTime/currentTime.js
- CurrentTime/index.html
This is the HTML and JavaScript code to run the current time in the browser, in digital format 00:00:00.
> Hacktoberfest: Add small app that shows current time in hh:min:sec format

- TicTacToe/TicTacToe.css
- TicTacToe/TicTacToe.html
Using tags <table> etc., to form a tic-tac-toe design while also taking help of CSS Selectors like "border" etc.
> Added a basic formation of a table tic-tac-toe

- animated_heading/css/style.css
- animated_heading/index.html
Wrote the code for Animated Heading using css. Used basic transitions and transform properties and added -moz, -o etc. for browser compatibility.
> Added css stylesheet, index.html for animated heading.

- Analog Clock/README.md
created a new README.md file for Analog Clock Project. #129
> Added README.md File #129

- gsap-loader/gsap-loader.html
> add gsap loader

- Absolute-Center-Fullscreen-Layout/index.html
Created an extra emphasis on the important words in the text.
> Updated index.html file

- Bootstrap Example HTML/css/example1.css
- Bootstrap Example HTML/css/example2.css
- Bootstrap Example HTML/css/example3.css
- Bootstrap Example HTML/css/example4.css
- Bootstrap Example HTML/css/example6.css
- Bootstrap Example HTML/css/example7.css
- Bootstrap Example HTML/css/example8.css
- Bootstrap Example HTML/css/example9.css
- Bootstrap Example HTML/example1.html
- Bootstrap Example HTML/example10.html
- Bootstrap Example HTML/example2.html
- Bootstrap Example HTML/example3.html
- Bootstrap Example HTML/example4.html
- Bootstrap Example HTML/example5.html
- Bootstrap Example HTML/example6.html
- Bootstrap Example HTML/example7.html
- Bootstrap Example HTML/example8.html
- Bootstrap Example HTML/example9.html
I added different examples of Bootstrap using HTML that I think that can be interesting.
> Added examples of Bootstrap with HTML

- Pink Panda Form
Hopefully you will accept this form into the project. Once again, learning how to do things as I go. I suppose the next step is to create the PHP document so that this can be submitted and then create that web page incorporating the footer and the form I have made. Let me know if you need any other information. Thanks!
> Create Pink Panda Form

- Convert-CSV-To-2DArray/index.html
- Convert-CSV-To-2DArray/methods.js
- Convert-CSV-To-2DArray/testing.js
- Interest Calculator/index.html
- Interest Calculator/interest.js
Heyy There 
I'm Adding Component for Convert CSV Data Into 2D Array
Thanks... :)
> Adding Convert-CSV-To-2DArray

- htmlcodenetflixclone
- netflixclone.css
> added html program of Netflix clone

- webpage basic/web page basic.html
Please kindly merge my pull request. Thanks
> web page basic added committed by Qausain Manzoor

- DrawingApp/drawingscript.js
- DrawingApp/drawingstyle.css
- DrawingApp/index.html
Made a Drawing app with the use of HTML , CSS , JS.
> Made a Drawing app with the use of HTML , CSS , JS.

- score-Maintainer/operations arrays.html
- score-Maintainer/scrore maintainer.css
- score-Maintainer/xxx.js
I have added a score maintaining webpage with options to dark and light mode and option to change the maximum limit up to which the game will go on.
> Added webpage for score maintaining

- BASIC HTML PAGES/Registration_form.html
- Simple Landing Page/index.html
> add input 

- canvashtml.html
This New file project to make full fun project that which is made in html canvas
If any one to chnage he/shw can
> canvasHtml.html

- neomorphism_switch/index.html
- neomorphism_switch/main.js
- neomorphism_switch/style.css
Toggle draggable switch using the latest neomorphism trend.
> Neomorphism Switch

- Footer
This is my first attempt to create a footer. It's nothing fancy at this stage and quite happy for the colour to be changed (I went for pink as it seemed fun). From here, I will try my best to contribute more complicated things. But I appreciate your time and hope that you'll merge this footer with the project. My next step is to build a form and then a whole page (hopefully)
> Basic Footer

- Flex Panel Gallery/index.html
- Flex Panel Gallery/stylesheet.css
**Interactive Gallery using Flexbox and dynamic animations**
_The UI_
> Flex Panel Gallery added (Theme : FAANG)

- MyWebsite/index.html
- Tailwind-Homepage/index.html
Initialized with index file filled with html5 tagging.
> Started a new project to design homepage

- covid-19 HTML/Capstone_Covid_19.html
Hey!! there,
Created an informative HTML page about COVID-19
> Covid-19 Html Page

- calculator using html and css
this calculator is built using HTML and CSS.
> Create calculator using html and css

- Stopwatch/index.html
- Stopwatch/main.js
- Stopwatch/style.css
A simple stopwatch implementation using html,css and javascript.
> Added stop watch

- Flip-Cards/flip-card.js
- Flip-Cards/index.html
- Flip-Cards/style.css
A simple card flip script and html markup in a grid with card growing to accommodate flipped content.
> Flip Cards

- Basic Webpage/index.html
- input-anim/index.html
- input-anim/style.css
Added a new input animation file
> Added Input-anim File

- thank-you/Simple Form webpage
Bringing together all of the other pieces - footer, header, form into one page.
> Create Simple Form webpage

- Music Player/WUMD.html
- Music Player/ghrpardesiya.html
- Music Player/kadkegallasy.html
- Music Player/shapeofu.html
- Music Player/songss.css
- Music Player/tareefan.html
- Music Player/treatubttr.html
I have created a music player with basic HTML &CSS.
> Music Player 
